os: linux
dist: focal
language: bash

matrix:
  include:
    - language: c
      dist: focal
      before_script:
        - cd c
      script:
        - docker build -t c-build .
      install:
        - docker run --rm c-build

    - language: cpp
      dist: focal
      before_script:
        - cd cpp
      script:
        - docker build -t cpp-build .
      install:
        - docker run --rm cpp-build

    - language: shell
      dist: focal
      before_script:
        - cd bash
      script:
        - docker build -t bash-build .
      install:
        - docker run --rm bash-build

    - language: dart
      dist: focal
      before_script:
        - cd dart
      script:
        - docker build -t dart-build .
      install:
        - docker run --rm dart-build
