os: linux

dist: focal

services:
     - docker
    
install:
     - cd c
     - docker build -t c-build .
   
script:
     - docker run --rm c-build

install:
     - cd cpp
     - docker build -t cpp-build .

script:
     - docker run --rm cpp-build