# Removed PHP and JS bcoz of zero test case.
os: linux
services: docker
language: shell

jobs:
  include:
    - before_script:
        - cd ada
      script:
        - docker build -t ada-build .
        - docker run --rm ada-build

    - before_script:
        - cd bash
      script:
        - docker build -t bash-build .
        - docker run --rm bash-build

    - before_script:
        - cd c
      script:
        - docker build -t c-build .
        - docker run --rm c-build

    - before_script:
        - cd common-lisp
      script:
        - docker build -t clisp-build .
        - docker run --rm clisp-build        

    - before_script:
        - cd cpp
      script:
        - docker build -t cpp-build .
        - docker run --rm cpp-build

    - before_script:
        - cd dart
      script:
        - docker build -t dart-build .
        - docker run --rm dart-build

    - before_script:
        - cd elixir
      script:
        - docker build -t elixir-build .
        - docker run --rm elixir-build

    - before_script:
        - cd erlang
      script:
        - docker build -t erlang-build .
        - docker run --rm erlang-build

    - before_script:
        - cd fortran
      script:
        - docker build -t fortran-build .
        - docker run --rm fortran-build

    - before_script:
        - cd go
      script:
        - docker build -t go-build .
        - docker run --rm go-build

    - before_script:
        - cd haskell
      script:
        - docker build -t haskell-build .
        - docker run --rm haskell-build

    - before_script:
        - cd icon
      script:
        - docker build -t icon-build .
        - docker run --rm icon-build

    - before_script:
        - cd java
      script:
        - docker build -t java-build .
        - docker run --rm java-build

    - before_script:
        - cd julia
      script:
        - docker build -t julia-build .
        - docker run --rm julia-build

    - before_script:
        - cd kotlin
      script:
        - docker build -t kotlin-build .
        - docker run --rm kotlin-build

    - before_script:
        - cd lisp
      script:
        - docker build -t lisp-build .
        - docker run --rm lisp-build

    - before_script:
        - cd lua
      script:
        - docker build -t lua-build .
        - docker run --rm lua-build

    - before_script:
        - cd node
      script:
        - docker build -t node-build .
        - docker run --rm node-build

    - before_script:
        - cd objective-c
      script:
        - docker build -t objc-build .
        - docker run --rm objc-build

    - before_script:
        - cd perl
      script:
        - docker build -t perl-build .
        - docker run --rm perl-build

    - before_script:
        - cd php
      script:
        - docker build -t php-build .
        - docker run --rm php-build

    - before_script:
        - cd python/worker
      script:
        - docker build -t python-build .
        - docker run --rm python-build

    - before_script:
       - cd python/web
      script:
       - docker build -t pythonweb-build .
       - docker run --rm pythonweb-build

    - before_script:
        - cd r
      script:
        - docker build -t r-build .
        - docker run --rm r-build

    - before_script:
        - cd rust
      script:
        - docker build -t rust-build .
        - docker run --rm rust-build

    - before_script:
        - cd scala
      script:
        - docker build -t scala-build .
        - docker run --rm scala-build

    - before_script:
        - cd swift
      script:
        - docker build -t swift-build .
        - docker run --rm swift-build