matrix:
  include:
    - language: c
      before_script:
        - cd c
      script:
        - docker build -t c-build .
        - docker run --rm c-build
    - language: cpp
      before_script:
        - cd cpp
      script:
        - docker build -t cpp-build .
        - docker run --rm cpp-build